### ISSUE TITLE
research_rabbit.py code is not working

### ISSUE THREAD

**Issue by probe365** [langchain-ai/research-rabbit#1]
Hi Lance,

I would like to ask you why the code provided here is difference from that one you showed in the youtube.com. I tried to run the research_rabbit.py code provided here, but it is not working. Please, let me know what I missed.

Thanks a lot.
Paulo

**Comment by rlancemartin** [comment]
What error do you see?

Running this from scratch on a fresh pull of the repo works as expected for me:

1/ It will use `llama3.2` and Ollama by default. Make sure this is set pulled.

2/ Make sure TAVILY_API_KEY is set.

```
curl -LsSf https://astral.sh/uv/install.sh | sh
git clone https://github.com/langchain-ai/research-rabbit.git
cd research-rabbit
uvx --refresh --from "langgraph-cli[inmem]" --with-editable . --python 3.11 langgraph dev
```

**Comment by probe365** [comment]
Thanks for your prompt response.

The error was:
File "C:\research-rabbit\src\research_rabbit\research_rabbit.py", line 10, in <module>
    from research_rabbit.configuration import Configuration
ModuleNotFoundError: No module named 'research_rabbit.configuration'; 'research_rabbit' is not a package

After I excluded the 'research_rabbit.' from the imports the code started to works without errors.

Thanks!
