### ISSUE TITLE
Windows Support Availability and Roadmap

### ISSUE THREAD

**Issue by bluesship** [langchain-ai/research-rabbit#2]
Hello,

I have two questions regarding Windows support for Research Rabbit:

1. Does Research Rabbit currently support local deployment on Windows systems? I noticed that the documentation mainly focuses on Linux/Unix environments.

2. If Windows is not currently supported, is there any plan to add Windows compatibility in the future roadmap?

Thank you for this great project, and looking forward to your response.

**Comment by rlancemartin** [comment]
Hi! This doesn't use the LangGraph Studio desktop app, which is available for Mac only. 

This simply runs a LangGraph server locally and spin ups Studio in your browser. 

This workflow should all work on Windows cc: @hinthornw. 

Follow the below:
```
curl -LsSf https://astral.sh/uv/install.sh | sh
git clone https://github.com/langchain-ai/research-rabbit.git
cd research-rabbit
uvx --refresh --from "langgraph-cli[inmem]" --with-editable . --python 3.11 langgraph dev
```

**Comment by hinthornw** [comment]
Yeah this should already be supported. 

The windows installation of `uv` (used in Lnace's snippet above) wuold be either using pip:
```shell
pip install -U uv
```
or powershell or something
```
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

the rest should be similar
